In [1]:
import torch as tr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
x = tr.empty(2,3)
x

tensor([[4.1723e-08, 5.2898e+22, 1.3446e+22],
        [6.4830e-10, 2.1065e-07, 4.2093e+21]])

In [4]:
x = tr.rand(2,2)
x

tensor([[0.6568, 0.8967],
        [0.9619, 0.2947]])

In [6]:
x = tr.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [8]:
x = tr.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [9]:
x = tr.ones(2,2, dtype = tr.int)
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [10]:
x = tr.ones(2,2, dtype = tr.double)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [11]:
x = tr.ones(2,2, dtype = tr.float16)
x

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)

In [12]:
x.size()

torch.Size([2, 2])

In [13]:
list_tensor = [2.5,0.1]
x = tr.tensor(list_tensor)
x

tensor([2.5000, 0.1000])

In [14]:
x = tr.rand(2,2)
y = tr.rand(2,2)
print(y)
z = x+y
z1 = tr.add(x,y)
print(z)
print(z1)
print(y.add_(x))

tensor([[0.6914, 0.2477],
        [0.5059, 0.3124]])
tensor([[1.3128, 0.7593],
        [1.0389, 0.8846]])
tensor([[1.3128, 0.7593],
        [1.0389, 0.8846]])
tensor([[1.3128, 0.7593],
        [1.0389, 0.8846]])


In [15]:
z_ = x-y
z__ = tr.sub(x,y)
print(z_)
print(z__)


tensor([[-0.6914, -0.2477],
        [-0.5059, -0.3124]])
tensor([[-0.6914, -0.2477],
        [-0.5059, -0.3124]])


In [16]:
z_mul = x*y
z__mul = tr.mul(x,y)
print(z_mul)
print(z__mul)


tensor([[0.8157, 0.3885],
        [0.5537, 0.5061]])
tensor([[0.8157, 0.3885],
        [0.5537, 0.5061]])


In [17]:
print(y.mul_(x))

tensor([[0.8157, 0.3885],
        [0.5537, 0.5061]])


In [18]:
print(x/y)

tensor([[0.7617, 1.3169],
        [0.9626, 1.1305]])


In [19]:
print(tr.div(x,y))

tensor([[0.7617, 1.3169],
        [0.9626, 1.1305]])


In [20]:
x = tr.rand(5,3)
print(x)
print(x[:, 1])

tensor([[0.4802, 0.1225, 0.1332],
        [0.5722, 0.2442, 0.2511],
        [0.7423, 0.8930, 0.5272],
        [0.4251, 0.7749, 0.7682],
        [0.0657, 0.4867, 0.2678]])
tensor([0.1225, 0.2442, 0.8930, 0.7749, 0.4867])


In [21]:
print(x[1, :])

tensor([0.5722, 0.2442, 0.2511])


In [22]:
print(x[1,1])

tensor(0.2442)


In [24]:
print(x[1,1].item())

0.24422603845596313


In [25]:
z = tr.rand(4,4)
print(z)
y = z.view(16)
print(y)

tensor([[0.6776, 0.4113, 0.9398, 0.9005],
        [0.6902, 0.9422, 0.8943, 0.9885],
        [0.7683, 0.2569, 0.9809, 0.8144],
        [0.4830, 0.5389, 0.2109, 0.3686]])
tensor([0.6776, 0.4113, 0.9398, 0.9005, 0.6902, 0.9422, 0.8943, 0.9885, 0.7683,
        0.2569, 0.9809, 0.8144, 0.4830, 0.5389, 0.2109, 0.3686])


In [26]:
y = z.view(-1,8)
print(y.size())

torch.Size([2, 8])


In [27]:
print(y)

tensor([[0.6776, 0.4113, 0.9398, 0.9005, 0.6902, 0.9422, 0.8943, 0.9885],
        [0.7683, 0.2569, 0.9809, 0.8144, 0.4830, 0.5389, 0.2109, 0.3686]])


In [28]:
a = tr.ones(5)
p = a.numpy()
print(a)
print(p)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(p)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [30]:
a = np.ones(5)
print(a)
b = tr.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [31]:
a +=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [33]:
if tr.cuda.is_available():
    device = tr.device("cuda")
    x = tr.ones(5, device = device)
    y = tr.ones(5)
    y = y.to(device)
    z = x+y
   # z.numpy() #numpy handles only cpu tensor
    z = z.to("cpu")




In [34]:
x = tr.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


### Autograds

In [35]:
x = tr.randn(3)
print(x)
y = tr.randn(3, requires_grad = True)
print(y)


tensor([-0.5133,  0.5609,  0.9394])
tensor([-0.3433, -1.5667, -0.7841], requires_grad=True)


In [46]:
z = y + 2
print(z)


tensor([1.6567, 0.4333, 1.2159], grad_fn=<AddBackward0>)


In [47]:
z = z*z*2
print(z)


tensor([5.4895, 0.3755, 2.9569], grad_fn=<MulBackward0>)


In [48]:
z = z.mean()
print(z)


tensor(2.9406, grad_fn=<MeanBackward0>)


In [49]:
z.backward() # dm/dy chain rule jakovian matrix only for scalar outputs
print(y.grad)

tensor([4.4179, 1.1554, 3.2424])


In [50]:
v = tr.tensor([0.1,1.0,0.001], dtype = tr.float32)
z.backward()
print(y.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [52]:
w = tr.randn(3, requires_grad = True)

print(w)
w.requires_grad_(False)
print(w)

tensor([ 0.7670,  1.0145, -0.5036], requires_grad=True)
tensor([ 0.7670,  1.0145, -0.5036])


In [53]:
e = w.detach()
print(e)

tensor([ 0.7670,  1.0145, -0.5036])


In [54]:
with tr.no_grad():
    r = w+2
    print(r)

tensor([2.7670, 3.0145, 1.4964])


In [58]:
weights = tr.ones(4, requires_grad = True)
for epoch in range(4):
    model_output = (weights*3).sum()

    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [59]:
wt  =tr.ones(4, requires_grad = True)
optimizer = tr.optim.SGD(wt, lr = 0.01)
optimizer.step()
optimizer.zero_grad()


TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [60]:
wt  =tr.ones(4, requires_grad = True)
z.backward()
wt.grad.zero_()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

## Backpropagation

In [61]:
x = tr.tensor(1.0)
y = tr.tensor(2.0)
w = tr.tensor(1.0, requires_grad=True)

# forward pass
y_hat = w*x
loss = (y_hat-y)**2

print(loss)
loss.backward()
print(w.grad)



tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


### Gradient descent

In [64]:
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)

w = 0.0
# model prediction
def forward(x):
    return w*x

# loss
def loss(y, y_predicted):
    return ((y_predicted-y)**2).mean()

# gradient
# MSE = 1/N *(w*x-y)**2
# dj/dw = 1/N 2x (w*x -y)
def gradient(x, y, y_predicted):
    return np.dot(2*x, y_predicted-y).mean()

print(f"Prediction before training : f(5) = {forward(5):.3f}")

learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # prediction = forward pass
    y_pred = forward(X)
    l = loss(Y, y_pred)
    dw = gradient(X,Y,y_pred)

    w -= learning_rate *dw
    
    if epoch %1 ==0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:,.8f}')


print(f"Prediction after training : f(5) = {forward(5):.3f}")



Prediction before training : f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 2: w = 1.680, loss = 4.79999924
epoch 3: w = 1.872, loss = 0.76800019
epoch 4: w = 1.949, loss = 0.12288000
epoch 5: w = 1.980, loss = 0.01966083
epoch 6: w = 1.992, loss = 0.00314570
epoch 7: w = 1.997, loss = 0.00050332
epoch 8: w = 1.999, loss = 0.00008053
epoch 9: w = 1.999, loss = 0.00001288
epoch 10: w = 2.000, loss = 0.00000206
epoch 11: w = 2.000, loss = 0.00000033
epoch 12: w = 2.000, loss = 0.00000005
epoch 13: w = 2.000, loss = 0.00000001
epoch 14: w = 2.000, loss = 0.00000000
epoch 15: w = 2.000, loss = 0.00000000
epoch 16: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 18: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
epoch 20: w = 2.000, loss = 0.00000000
Prediction after training : f(5) = 10.000


In [68]:
X = tr.tensor([1,2,3,4], dtype=tr.float32)
Y = tr.tensor([2,4,6,8], dtype=tr.float32)

w = tr.tensor(0.0, dtype = tr.float32, requires_grad= True)

# model prediction
def forward(x):
    return w*x

# loss
def loss(y, y_predicted):
    return ((y_predicted-y)**2).mean()

# # gradient
# # MSE = 1/N *(w*x-y)**2
# # dj/dw = 1/N 2x (w*x -y)
# def gradient(x, y, y_predicted):
#     return np.dot(2*x, y_predicted-y).mean()

print(f"Prediction before training : f(5) = {forward(5):.3f}")

learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # prediction = forward pass
    y_pred = forward(X)
    l = loss(Y, y_pred)

    # gradient = backward pass
    l.backward() # dl/dw
    with tr.no_grad():
        w -= learning_rate * w.grad
    # zero gradients
    w.grad.zero_()
    
    if epoch %10 ==0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:,.8f}')


print(f"Prediction after training : f(5) = {forward(5):.3f}")


Prediction before training : f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training : f(5) = 10.000
