## PYTORCH
### Dated - 12/10/2022

In [1]:
import torch as tr

In [2]:
tr.__version__

'1.12.1'

In [6]:
x = tr.ones(2,2)
print(x.dtype)

torch.float32


In [7]:
y = tr.ones(2,2, dtype= tr.float16)
print(y.dtype)

torch.float16


In [8]:
a = tr.tensor([2.5, 0.1,5.01])
print(a)

tensor([2.5000, 0.1000, 5.0100])


In [9]:
s = tr.rand(2,2)
t = tr.rand(2,2)
d = s+t
print(d)

tensor([[1.0659, 0.6288],
        [0.8162, 0.9959]])


In [10]:
t.add_(s)
print(t)

tensor([[1.0659, 0.6288],
        [0.8162, 0.9959]])


In [11]:
d = s-t
print(d)

tensor([[-0.7945, -0.3644],
        [-0.7561, -0.7239]])


In [12]:
d= tr.sub(s,t)
print(d)

tensor([[-0.7945, -0.3644],
        [-0.7561, -0.7239]])


In [13]:
d = tr.mul(s,t)
print(d)

tensor([[0.2893, 0.1663],
        [0.0490, 0.2708]])


In [14]:
d = s*t
print(d)

tensor([[0.2893, 0.1663],
        [0.0490, 0.2708]])


In [15]:
d = s/t
print(d)

tensor([[0.2546, 0.4205],
        [0.0736, 0.2731]])


In [16]:
d = tr.div(s,t)
print(d)

tensor([[0.2546, 0.4205],
        [0.0736, 0.2731]])


In [17]:
h = tr.rand(5,3)
print(h)

tensor([[0.0900, 0.0349, 0.7377],
        [0.7825, 0.9062, 0.5222],
        [0.2162, 0.4722, 0.7915],
        [0.3781, 0.7820, 0.7955],
        [0.7181, 0.7108, 0.5080]])


In [18]:
print(h[:, 0])

tensor([0.0900, 0.7825, 0.2162, 0.3781, 0.7181])


In [19]:
print(h[1,:])

tensor([0.7825, 0.9062, 0.5222])


In [20]:
print(h[1,1].item())

0.9061926007270813


In [21]:
b = tr.rand(4,4)
print(b)

tensor([[0.0935, 0.4352, 0.5204, 0.8644],
        [0.1696, 0.6298, 0.0659, 0.5153],
        [0.5292, 0.9030, 0.1862, 0.2587],
        [0.4011, 0.7664, 0.1121, 0.0519]])


In [22]:
i  =b.view(16)
print(i)

tensor([0.0935, 0.4352, 0.5204, 0.8644, 0.1696, 0.6298, 0.0659, 0.5153, 0.5292,
        0.9030, 0.1862, 0.2587, 0.4011, 0.7664, 0.1121, 0.0519])


In [23]:
i = b.view(-1, 8)
print(i)

tensor([[0.0935, 0.4352, 0.5204, 0.8644, 0.1696, 0.6298, 0.0659, 0.5153],
        [0.5292, 0.9030, 0.1862, 0.2587, 0.4011, 0.7664, 0.1121, 0.0519]])


In [24]:
import numpy as np

In [25]:
a = tr.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()

In [27]:
print(type(b))

<class 'numpy.ndarray'>


In [28]:
print(type(a))

<class 'torch.Tensor'>


In [29]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [30]:
a = np.ones(5)
print(a)
b = tr.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [31]:
a +=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [34]:
if tr.cuda.is_available():
    device = tr.device('cuda')
    x = tr.ones(5, device = device)
    y = tr.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")
    
print(z)

NameError: name 'z' is not defined

In [33]:
# pip install cvlib

In [35]:
tr.cuda.is_available()

False

In [36]:
x = tr.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [38]:
a= 5
b =5
print("y " if a ==b else "n")

y 
