## Save and Load model

[SOURCE] = https://www.youtube.com/watch?v=c36lUUr864M

In [1]:
import torch as tr
import torch.nn as nn

In [ ]:
# complete model
# tr.save(model, PATH) 

# model class must be defined in somewhere
# model = tr.load(PATH)
# model.eval()

### STATE DICT ### preferred way
# tr.save(model.state_dict(), PATH)

# model must be created again with parameters
# model = Model(*args, **kwargs)
# model.load_state_dict(tr.load(PATH))
# model.eval()


In [3]:
class Model(nn.Module):
    def __init__(self, n_input_featrues):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_featrues, 1)

    def forward(self, x):
        y_pred = tr.sigmoid(self.linear(x))
        return y_pred

model = Model(n_input_featrues=6)

# train the model 


In [4]:
# lesy method to save the model
FILE = "./pytorch_models/model.pth"
tr.save(model, FILE)

In [6]:
loaded_Model = tr.load(FILE)
loaded_Model.eval()

for params in loaded_Model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.2395,  0.2029,  0.1473, -0.0193,  0.0214,  0.0827]],
       requires_grad=True)
Parameter containing:
tensor([0.0392], requires_grad=True)


In [7]:
# preferred way to save and load model
FILE1 = "./pytorch_models/model_state_dict.pth"

tr.save(model.state_dict(), FILE1)

In [8]:
loaded_sd_Model = Model(n_input_featrues=6)
loaded_sd_Model.load_state_dict(tr.load(FILE1))
loaded_sd_Model.eval()

for params in loaded_sd_Model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.2395,  0.2029,  0.1473, -0.0193,  0.0214,  0.0827]],
       requires_grad=True)
Parameter containing:
tensor([0.0392], requires_grad=True)


In [9]:
print(model.state_dict())

OrderedDict([('linear.weight', tensor([[ 0.2395,  0.2029,  0.1473, -0.0193,  0.0214,  0.0827]])), ('linear.bias', tensor([0.0392]))])


In [10]:
lr = 0.01
optim = tr.optim.SGD(model.parameters(), lr = lr)
print(optim.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'params': [0, 1]}]}


In [11]:
checkpoint = {
    "epoch" : 90,
    "model_state" : model.state_dict(),
    "optim_state" : optim.state_dict(),
}

tr.save(checkpoint, "./pytorch_models/chkpt.pth")

In [12]:
loaded_checkpoint = tr.load("./pytorch_models/chkpt.pth")
epoch = loaded_checkpoint["epoch"]

model = Model(n_input_featrues=6)
optimizer = tr.optim.SGD(model.parameters(),lr = 0)

model.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint["optim_state"])

print(optimizer.state_dict())


{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'params': [0, 1]}]}


In [ ]:
# ############---SAVE ON GPU AND LOAD ON CPU---#############

# device = tr.device("cuda")
# model.to(device)
# tr.save(model.state_dict(), PATH)

# device = tr.device("cpu")
# model.Model(*args, **kwargs)
# model.load_state_dict(tr.load(PATH, map_location=device))



In [ ]:
# ############---SAVE ON GPU AND LOAD ON GPU---#############

# device = tr.device("cuda")
# model.to(device)
# tr.save(model.state_dict(), PATH)

# model.Model(*args, **kwargs)
# model.load_state_dict(tr.load(PATH))
# model.to(device)


In [ ]:
# ############---SAVE ON CPU AND LOAD ON GPU---#############

# tr.save(model.state_dict(), PATH)

# device = tr.device("cuda")

# model.Model(*args, **kwargs)
# model.load_state_dict(tr.load(PATH,  map_location="cuda:0"))
# model.to(device)
